logging:
  level:
    com.zaxxer.hikari: warn
    eu.europa.ec.sante.ehdsi.openncp: info
    org.hibernate: warn
spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    default:
      jndi-name: java:comp/env/jdbc/ConfMgr
    atna:
      jndi-name: java:comp/env/jdbc/OPEN_ATNA
    eadc:
      jndi-name: java:comp/env/jdbc/EADC
    database: default
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jackson:
    default-property-inclusion: non_empty
  mail:
    host: 127.0.0.1
    port: 25
    username: email@ehdsi.eu
    password: password
application:
  mail:
    from: sante-ehealth-dsi-support@ec.europa.eu
  portal:
    base-url: http://127.0.0.1:8080/openncp-gateway
  security:
    jwt:
      secret: S7U418zVNeAIRmznNyNQec7eimPD0qEv