debug: false
logging:
  level:
     org.hibernate: ERROR
     org.springframework.web.client: DEBUG
spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://127.0.0.1/jerome_property?useSSL=false
    username: root
    password: MySqlAdminPwd
    driver-class-name: com.mysql.jdbc.Driver
openncp:
  property-file:
    path: /opt/ehealth-openncp/ehealth-setup/openncp-configuration-utility/openncp-configuration.properties
profiles:
   active: mysql