debug: false
ehealth:
  termserver:
    base-url: https://webgate.acceptance.ec.europa.eu/ehealth-term-server
    username: system@localhost
    password: 123456
logging:
  level:
     org.hibernate: ERROR
openncp:
  ltrdb:
    host:
    port:
    username:
    password:
    database-name:
spring:
  datasource:
    url: jdbc:oracle:thin:@//s-sanco-db-dev.sanco.cec.eu.int:1521/SANTEDEV1.sanco.cec.eu.int
    username: ehealth_termserver
    password: ehealth_termserver
    driver-class-name: oracle.jdbc.OracleDriver
  profiles:
    active: oracle