tsam-sync:
  database:
    backup:
  datasource:
    host:
    port:
    username:
    password:
    database:
  proxy:
    host:
    port:
    username:
    password:
  cts:
    url:
    username:
    password: