debug: false
ehealth:
  termserver:
    base-url: https://webgate.acceptance.ec.europa.eu/ehealth-term-server
    username: pt@system
    password: 123456
logging:
  level:
     org.hibernate: ERROR
openncp:
  ltrdb:
    host: 127.0.0.1
    port: 3306
    username: openncp_dev
    password: MyOpenncpPwd
    database-name: ehealth_ltrdb_dev
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ehealth_ltrdb_dev
    username: openncp_dev
    password: MyOpenncpPwd
    driver-class-name: com.mysql.jdbc.Driver
  profiles:
    active: mysql