logging:
  level:
    com.zaxxer.hikari: warn
    eu.europa.ec.sante.ehdsi.openncp: info
    org.hibernate: warn
spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
  datasource:
    default:
      jndi-name: java:comp/env/jdbc/ConfMgr
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jackson:
    default-property-inclusion: non_empty
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  error:
    include-message: always
app:
  name: translations and mappings ws
  api:
    title: Translations and mappings Webservice
    version: '@project.version@-@timestamp@'
    description: Translations and mappings Webservice
    base-package: eu.europa.ec.sante.ehdsi.openncp.tm.ws
    contact-name: eHealth DSI Support
    contact-email: sante-ehealth-dsi-support@ec.europa.eu
    swagger:
      enable: true