hapi:
  fhir:
    version: r4
    server:
      path: /fhir
    rest:
      server-name: hapi-fhir-spring-boot-sample-server-jersey
      server-version: 1.0.0
      implementation-description: myHealth@EU FHIR POC
      default-response-encoding: json
      e-tag-support: enabled
      default-pretty-print: true
    validation:
      enabled: true
      request-only: true
    openapi:
      enabled: true
      secured: false
fhirserver:
  url: http://localhost:8081/fhir/
fhir:
  server:
    inclusion: false
logging:
  level:
    com.zaxxer.hikari: warn
    eu.europa.ec.sante.openncp: info
    org.hibernate: warn
spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
  datasource:
    jndi:
      tsam:
        jndiName: java:comp/env/jdbc/TSAM
      properties:
        jndiName: java:comp/env/jdbc/ConfMgr
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jackson:
    default-property-inclusion: non_empty
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  error:
    include-message: always
app:
  name: translations and mappings ws
  api:
    title: Translations and mappings Webservice
    version: '@project.version@-@timestamp@'
    description: Translations and mappings Webservice
    base-package: eu.europa.ec.sante.openncp.application.transformation
    contact-name: eHealth DSI Support
    contact-email: sante-ehealth-dsi-support@ec.europa.eu
    swagger:
      enable: true