spring:
  jpa:
    properties:
      hibernate.dialect: ${tsam-sync.datasource.dialect}
  datasource:
    driver-class-name: ${tsam-sync.datasource.driver}
    url: jdbc:mariadb://${tsam-sync.datasource.host}:${tsam-sync.datasource.port}/${tsam-sync.datasource.database}