spring:
  datasource:
    properties:
      jndi-name: jdbc/ConfMgr
      url: jdbc:mysql://localhost:3307/ehealth_properties?allowPublicKeyRetrieval=true&useSSL=false
      username: root
      password: Password1
      driver-class-name: com.mysql.cj.jdbc.Driver
    tsam:
      jndi-name: jdbc/TSAM
      url: jdbc:mysql://localhost:3307/ehealth_ltrdb?allowPublicKeyRetrieval=true&useSSL=false
      username: root
      password: Password1
      driver-class-name: com.mysql.cj.jdbc.Driver

