hapi:
  fhir:
    version: r4
    server:
      path: /fhir
    rest:
      server-name: hapi-fhir-spring-boot-sample-server-jersey
      server-version: 1.0.0
      implementation-description: myHealth@EU FHIR POC
      default-response-encoding: json
      e-tag-support: enabled
      default-pretty-print: true
    validation:
      enabled: true
      request-only: true
    openapi:
      enabled: true
      secured: false
management:
  security:
    enabled: false
logging:
  level:
    ca.uhn.fhir.jaxrs: debug
fhirserver:
  url: http://localhost:8081/fhir/
spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: 'jdbc:mysql://localhost:3307/ehealth_properties'
    username: root
    password: Password1
    driverClassName: com.mysql.cj.jdbc.Driver
    jndi:
      tsam:
        jndiName: java:comp/env/jdbc/TSAM
        expected-type: javax.sql.DataSource
      properties:
        jndiName: java:comp/env/jdbc/ConfMgr
        expected-type: javax.sql.DataSource
server:
  port: 8888
