package eu.europa.ec.sante.openncp.common;

public enum Constant {

    SERVER_IP("SERVER_IP"),
    HOME_COMM_ID("HOME_COMM_ID"),
    COUNTRY_CODE("COUNTRY_CODE"),
    COUNTRY_NAME("COUNTRY_NAME"),
    COUNTRY_PRINCIPAL_SUBDIVISION("COUNTRY_PRINCIPAL_SUBDIVISION"),
    LANGUAGE_CODE("LANGUAGE_CODE"),
    TRUSTSTORE_PATH("TRUSTSTORE_PATH"),
    TRUSTSTORE_PASSWORD("TRUSTSTORE_PASSWORD"),
    SP_KEYSTORE_PATH("SP_KEYSTORE_PATH"),
    SP_KEYSTORE_PASSWORD("SP_KEYSTORE_PASSWORD"),
    SP_PRIVATEKEY_ALIAS("SP_PRIVATEKEY_ALIAS"),
    SP_PRIVATEKEY_PASSWORD("SP_PRIVATEKEY_PASSWORD"),
    SC_KEYSTORE_PATH("SC_KEYSTORE_PATH"),
    SC_KEYSTORE_PASSWORD("SC_KEYSTORE_PASSWORD"),
    SC_PRIVATEKEY_ALIAS("SC_PRIVATEKEY_ALIAS"),
    SC_PRIVATEKEY_PASSWORD("SC_PRIVATEKEY_PASSWORD"),
    NCP_SIG_KEYSTORE_PATH("NCP_SIG_KEYSTORE_PATH"),
    NCP_SIG_KEYSTORE_PASSWORD("NCP_SIG_KEYSTORE_PASSWORD"),
    NCP_SIG_PRIVATEKEY_ALIAS("NCP_SIG_PRIVATEKEY_ALIAS"),
    NCP_SIG_PRIVATEKEY_PASSWORD("NCP_SIG_PRIVATEKEY_PASSWORD"),
    ABUSE_UNIQUE_PATIENT_REQUEST_THRESHOLD("ABUSE_UNIQUE_PATIENT_REQUEST_THRESHOLD"),
    ABUSE_UNIQUE_PATIENT_REFERENCE_REQUEST_PERIOD("ABUSE_UNIQUE_PATIENT_REFERENCE_REQUEST_PERIOD"),
    ABUSE_UNIQUE_POC_REQUEST_THRESHOLD("ABUSE_UNIQUE_POC_REQUEST_THRESHOLD"),
    ABUSE_UNIQUE_POC_REFERENCE_REQUEST_PERIOD("ABUSE_UNIQUE_POC_REFERENCE_REQUEST_PERIOD"),
    ABUSE_ALL_REQUEST_THRESHOLD("ABUSE_ALL_REQUEST_THRESHOLD"),
    ABUSE_ALL_REQUEST_REFERENCE_REQUEST_PERIOD("ABUSE_ALL_REQUEST_REFERENCE_REQUEST_PERIOD"),
    ABUSE_SCHEDULER_TIME_INTERVAL("ABUSE_SCHEDULER_TIME_INTERVAL"),
    ABUSE_SCHEDULER_ENABLE("ABUSE_SCHEDULER_ENABLE"),
    JWT_SECRET("JWT_SECRET");


    private final String constantkey;

    Constant(String constantKey) {
        this.constantkey = constantKey;
    }

    public String getKey() {
        return constantkey;
    }
}
