logging:
  level:
    com.zaxxer.hikari: error
    org.apache.http: error
    org.hibernate: error
    org.springframework: error
spring:
  main:
    allow-circular-references: true
  datasource:
    datasource1:
      username: ${tsam-sync.datasource.username}
      password: ${tsam-sync.datasource.password}
    datasource2:
      username: ${tsam-sync.datasource-ehealth-properties.username}
      password: ${tsam-sync.datasource-ehealth-properties.password}
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

tsam-sync:
  database:
    backup: true
  pageable:
    default-page-size: 250
  datasource-ehealth-properties:
    host: 127.0.0.1
    port: 3306
    username: username
    password: password
    database: ehealth_properties
  datasource:
    dialect: org.hibernate.dialect.MySQL8Dialect
    driver: com.mysql.cj.jdbc.Driver
    timezone: Europe/Brussels

