debug: false
spring:
  datasource:
    url: jdbc:oracle:thin:@//s-sanco-db-dev.sanco.cec.eu.int:1521/SANTEDEV1.sanco.cec.eu.int
    username: ehealth_termserver
    password: ehealth_termserver
    driver-class-name: oracle.jdbc.OracleDriver